# Copyright (c) 2016 Kazumasa Kohtaka. All rights reserved.
# This file is available under the MIT license.

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: skydns
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: skydns
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '9090'
    spec:
      containers:
      - name: etcd
        image: quay.io/coreos/etcd:v3.0.15
      - name: skydns
        image: skynetservices/skydns:2.5.3a
        env:
        - name: ETCD_MACHINES
          value: http://127.0.0.1:2379
        - name: PROMETHEUS_PORT
          value: '9090'
        ports:
        - name: dns
          containerPort: 53
          protocol: UDP
        - name: dns-tcp
          containerPort: 53
          protocol: TCP
